### ISSUE TITLE
How to handle app with no extension

### ISSUE THREAD

**Issue by dceejay** [lfortin/node-cgi-core#2]
If I try to call an app with no extension - eg mapserv - then it assumes it's a directory and tries to add /index.js to it  .../mapserv/index.js

How do I specify not to add index.js ?

**Comment by lfortin** [comment]
Thanks for opening this issue, @dceejay, and for using `cgi-core`!

CGI scripts need to have their own file extension to be executed. Ex.: `mapserv.cgi`.

Then, the configuration for `extensions` must be defined accordingly. Also, if you wish to use standalone executables for a given file extension, it should be omitted in the `extensions` object.

Example of configuration:
```
import { createHandler } from "cgi-core";

// Example configuration where .cgi is omitted
const handler = createHandler({
  extensions: {
    "/usr/bin/perl": ["pl"],
    "/usr/bin/python": ["py"],
    "/usr/local/bin/node": ["js", "node"],
    // No extension mapping for mapserv.cgi, so it will be treated as a standalone executable
  },
});
```

Also, make sure that your standalone executables have the proper permissions to be executed by the server.

If you need more assistance with configuring specific paths or extensions, feel free to share your setup, and I can help further!

**Comment by dceejay** [comment]
hmmm - I didn't think it was mandatory for them to have an extension. Sure in the past they were usually called .cgi in order to help identify them... but I thought that got dropped ?   Ok - no biggie - I can create a dummy shell that calls the original (as it's cleaner for when the app (mapserv) gets updated)

**Comment by lfortin** [comment]
Oh, one more thing. If you wish to lookup for a script `index.cgi` instead of the default `index.js` inside directories, you may set this config: `indexExtension: "cgi"`.

For your use case, assuming you are running your HTTP server on a POSIX system, setting a symlink pointing to your script `mapserv` would probably be a good workaround:
```
ln -s mapserv mapserv.cgi
```
